# Generated by Django 4.2.11 on 2026-03-26 13:07

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Refuse')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitationlink',
            name='token',
            field=models.CharField(default=secrets.token_hex, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pays',
            field=models.CharField(blank=True, choices=[('benin', 'Benin'), ('cameroun', 'Cameroun'), ('cote_ivoire', "Cote d'Ivoire"), ('guinee', 'Guinee'), ('madagascar', 'Madagascar'), ('mali', 'Mali'), ('rca', 'RCA'), ('regional', 'Regional')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('analyste', 'Analyste ODAS'), ('moderateur', 'Moderateur pays'), ('contributeur', 'Contributeur'), ('bailleur', 'Bailleur')], default='contributeur', max_length=20),
        ),
    ]
