# Generated by Django 4.2.11 on 2026-03-25 12:57

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSignalement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20)),
                ('titre', models.CharField(max_length=300)),
                ('pays', models.CharField(choices=[('benin', 'Bénin'), ('cameroun', 'Cameroun'), ('cote_ivoire', "Côte d'Ivoire"), ('guinee', 'Guinée'), ('madagascar', 'Madagascar'), ('mali', 'Mali'), ('rca', 'RCA')], max_length=20)),
                ('date_evenement', models.DateField()),
                ('type_evenement', models.CharField(choices=[('legislatif', 'Législatif'), ('medias', 'Médias'), ('religieux', 'Religieux'), ('ong', 'ONG'), ('numerique', 'Numérique'), ('autre', 'Autre')], max_length=20)),
                ('criticite', models.CharField(choices=[('faible', 'Faible'), ('moderee', 'Modérée'), ('elevee', 'Élevée')], max_length=10)),
                ('description', models.TextField()),
                ('fiabilite', models.CharField(blank=True, choices=[('confirmee', 'Confirmée'), ('probable', 'Probable'), ('rumeur', 'Rumeur')], max_length=20)),
                ('confidentialite', models.CharField(choices=[('membres', 'Public membres'), ('moderateurs', 'Modérateurs'), ('staff', 'Staff ODAS')], default='membres', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('sources_url', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, editable=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical signalement',
                'verbose_name_plural': 'historical signalements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Narratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='signalements/')),
                ('nom_original', models.CharField(max_length=255)),
                ('taille', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=300)),
                ('pays', models.CharField(choices=[('benin', 'Bénin'), ('cameroun', 'Cameroun'), ('cote_ivoire', "Côte d'Ivoire"), ('guinee', 'Guinée'), ('madagascar', 'Madagascar'), ('mali', 'Mali'), ('rca', 'RCA')], max_length=20)),
                ('date_evenement', models.DateField()),
                ('type_evenement', models.CharField(choices=[('legislatif', 'Législatif'), ('medias', 'Médias'), ('religieux', 'Religieux'), ('ong', 'ONG'), ('numerique', 'Numérique'), ('autre', 'Autre')], max_length=20)),
                ('criticite', models.CharField(choices=[('faible', 'Faible'), ('moderee', 'Modérée'), ('elevee', 'Élevée')], max_length=10)),
                ('description', models.TextField()),
                ('fiabilite', models.CharField(blank=True, choices=[('confirmee', 'Confirmée'), ('probable', 'Probable'), ('rumeur', 'Rumeur')], max_length=20)),
                ('confidentialite', models.CharField(choices=[('membres', 'Public membres'), ('moderateurs', 'Modérateurs'), ('staff', 'Staff ODAS')], default='membres', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('sources_url', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('acteurs_lies', models.ManyToManyField(blank=True, related_name='signalements', to='actors.acteur')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
