# Generated by Django 4.2.11 on 2026-03-26 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejointe',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('document', 'Document'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsignalement',
            name='confidentialite',
            field=models.CharField(choices=[('membres', 'Public membres'), ('moderateurs', 'Moderateurs'), ('staff', 'Staff ODAS')], default='membres', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsignalement',
            name='criticite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moderee', 'Moderee'), ('elevee', 'Elevee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalsignalement',
            name='fiabilite',
            field=models.CharField(blank=True, choices=[('confirmee', 'Confirmee'), ('probable', 'Probable'), ('rumeur', 'Rumeur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsignalement',
            name='pays',
            field=models.CharField(choices=[('benin', 'Benin'), ('cameroun', 'Cameroun'), ('cote_ivoire', "Cote d'Ivoire"), ('guinee', 'Guinee'), ('madagascar', 'Madagascar'), ('mali', 'Mali'), ('rca', 'RCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsignalement',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Valide'), ('rejete', 'Rejete')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsignalement',
            name='type_evenement',
            field=models.CharField(choices=[('legislatif', 'Legislatif'), ('medias', 'Medias'), ('religieux', 'Religieux'), ('ong', 'ONG'), ('numerique', 'Numerique'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='confidentialite',
            field=models.CharField(choices=[('membres', 'Public membres'), ('moderateurs', 'Moderateurs'), ('staff', 'Staff ODAS')], default='membres', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='criticite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moderee', 'Moderee'), ('elevee', 'Elevee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='fiabilite',
            field=models.CharField(blank=True, choices=[('confirmee', 'Confirmee'), ('probable', 'Probable'), ('rumeur', 'Rumeur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='pays',
            field=models.CharField(choices=[('benin', 'Benin'), ('cameroun', 'Cameroun'), ('cote_ivoire', "Cote d'Ivoire"), ('guinee', 'Guinee'), ('madagascar', 'Madagascar'), ('mali', 'Mali'), ('rca', 'RCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Valide'), ('rejete', 'Rejete')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='type_evenement',
            field=models.CharField(choices=[('legislatif', 'Legislatif'), ('medias', 'Medias'), ('religieux', 'Religieux'), ('ong', 'ONG'), ('numerique', 'Numerique'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='SignalReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('utile', 'Utile'), ('a_verifier', 'A verifier'), ('prioritaire', 'Prioritaire')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='signals.signalement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignalFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='signals.signalement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_comments', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='signals.signalement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('creation', 'Creation'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('commentaire', 'Commentaire'), ('reaction', 'Reaction'), ('favori', 'Favori'), ('ressource', 'Ressource')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='signals.signalement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='signalreaction',
            constraint=models.UniqueConstraint(fields=('signalement', 'user', 'reaction_type'), name='unique_signal_reaction'),
        ),
        migrations.AddConstraint(
            model_name='signalfavorite',
            constraint=models.UniqueConstraint(fields=('signalement', 'user'), name='unique_signal_favorite'),
        ),
    ]
