# Generated by Django 4.2.11 on 2026-03-25 12:57

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, unique=True)),
                ('type_acteur', models.CharField(choices=[('intl', 'International'), ('local', 'Local/National'), ('media', 'Médias'), ('rel', 'Religieux')], max_length=10)),
                ('pays_operation', models.JSONField(default=list)),
                ('score_risque', models.IntegerField(default=0)),
                ('sources_financement', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score_risque'],
            },
        ),
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('financement', 'Financement'), ('partenaire', 'Partenariat'), ('media', 'Relais médiatique')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalActeur',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=300)),
                ('type_acteur', models.CharField(choices=[('intl', 'International'), ('local', 'Local/National'), ('media', 'Médias'), ('rel', 'Religieux')], max_length=10)),
                ('pays_operation', models.JSONField(default=list)),
                ('score_risque', models.IntegerField(default=0)),
                ('sources_financement', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical acteur',
                'verbose_name_plural': 'historical acteurs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
