# Generated by Django 4.2.11 on 2026-03-25 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalacteur',
            name='contribue_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalacteur',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connexion',
            name='cible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions_entrantes', to='actors.acteur'),
        ),
        migrations.AddField(
            model_name='connexion',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions_sortantes', to='actors.acteur'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='contribue_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acteurs_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acteur',
            name='narratifs',
            field=models.ManyToManyField(blank=True, to='signals.narratif'),
        ),
        migrations.AlterUniqueTogether(
            name='connexion',
            unique_together={('source', 'cible', 'type_lien')},
        ),
    ]
