# Generated by Django 4.2.11 on 2026-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='discours_messages_cles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acteur',
            name='strategie_mode_operatoire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acteur',
            name='zone_influence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalacteur',
            name='discours_messages_cles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalacteur',
            name='strategie_mode_operatoire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalacteur',
            name='zone_influence',
            field=models.TextField(blank=True),
        ),
    ]
