# Generated by Django 4.2.11 on 2026-03-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('rapports', 'Rapports'), ('guides', 'Guides pratiques'), ('outils', 'Outils'), ('formations', 'Formations'), ('juridique', 'Juridique')], max_length=20)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('multi', 'Multilingue')], default='fr', max_length=10)),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PPTX'), ('xlsx', 'XLSX'), ('docx', 'DOCX'), ('lien', 'Lien web')], max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('lien_externe', models.URLField(blank=True)),
                ('pays', models.CharField(blank=True, default='Tous', max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
